{% set name = "yardang" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/y/yardang/yardang-{{ version }}.tar.gz
  sha256: 681657a6d860ab7cec8792446de52046b32d4cb4bcc3c1892984c2ca8a16afc6

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - yardang = yardang.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - autodoc-pydantic
    - furo
    - myst-nb
    - packaging
    - rich
    - sphinx >=7.2.6,<9
    - sphinx-autoapi
    - sphinx-copybutton
    - sphinx-design
    - sphinxcontrib-mermaid >=1.1,<2
    - sphinx-reredirects
    - toml
    - typer

test:
  requires:
    - python {{ python_min }}
  commands:
    - yardang --help
  imports:
    - yardang.build
    - yardang.cli

about:
  home: http://github.com/python-project-templates/yardang
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easily generate sphinx documentation
  description: Easily generate sphinx documentation
  dev_url: https://github.com/python-project-templates/yardang

extra:
  recipe-maintainers:
    - timkpaine
