schema_version: 1

context:
  name: yardang
  version: "0.9.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/y/yardang/yardang-${{ version }}.tar.gz
  sha256: 736e3ee2b2857f520cbad235ebc7166c48ec45e62dcda89b4cefd02c131d2144

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - yardang = yardang.cli:main

requirements:
  host:
    - python ==${{ python_min }}
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - autodoc-pydantic
    - furo
    - myst-nb
    - packaging
    - rich
    - sphinx >=7.2.6,<9
    - sphinx-autoapi
    - sphinx-copybutton
    - sphinx-design
    - sphinxcontrib-mermaid >=2.0.0rc0,<2.1
    - sphinx-reredirects
    - toml
    - typer

tests:
  - python:
      imports:
        - yardang.build
        - yardang.cli
      pip_check: false
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - python ==${{ python_min }}
    script:
      - yardang --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Easily generate sphinx documentation
  description: Easily generate sphinx documentation
  homepage: http://github.com/python-project-templates/yardang
  repository: https://github.com/python-project-templates/yardang

extra:
  recipe-maintainers:
    - timkpaine
